// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250625041131_AddRoleToUser")]
    partial class AddRoleToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            CreatedAt = new DateTime(2025, 6, 25, 4, 11, 31, 784, DateTimeKind.Utc).AddTicks(8980),
                            Email = "somchai@example.com",
                            Name = "สมชาย ใจดี",
                            PasswordHash = "",
                            Role = "User"
                        },
                        new
                        {
                            Id = 2,
                            Age = 28,
                            CreatedAt = new DateTime(2025, 6, 25, 4, 11, 31, 784, DateTimeKind.Utc).AddTicks(8980),
                            Email = "somying@example.com",
                            Name = "สมหญิง รักงาน",
                            PasswordHash = "",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Age = 30,
                            CreatedAt = new DateTime(2025, 6, 25, 4, 11, 31, 784, DateTimeKind.Utc).AddTicks(8980),
                            Email = "john@example.com",
                            Name = "John Doe",
                            PasswordHash = "",
                            Role = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
