# ใช้ base image สำหรับ runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080 

# ใช้ SDK image สำหรับ build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Api.csproj", "."]
RUN dotnet restore "Api.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "Api.csproj" -c Release -o /app/build

# Publish app
FROM build AS publish
RUN dotnet publish "Api.csproj" -c Release -o /app/publish

# Final stage
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .


ENTRYPOINT ["dotnet", "Api.dll"]